### ISSUE TITLE
Definir UI pagina para agregar profesor

### ISSUE THREAD

**Issue by clustersnake** [RayTarazona/Codigo-fuente-#12]
![Image](https://github.com/RayTarazona/Codigo-fuente-/assets/167698073/53221e32-8ada-4ec8-af88-98053e3580bd)

![Image](https://github.com/RayTarazona/Codigo-fuente-/assets/167698073/630c39e9-5ee5-42a0-8acb-9bb48dd8376c)

**Comment by RayTarazona** [comment]
ahora vamos con el listado de profesores que que queremos que se vea por ahora. si deberíamos anexar una casilla de detalles. es importante recordar las fechas especiales. que se dan a inicio del año escolar y luego mensualmente se van agregando los días cívicos


![Image](https://github.com/RayTarazona/Codigo-fuente-/assets/167698073/4df11e8a-2971-4340-9c8b-797ef6305203)
